export const backgroundColor = (props) => props.theme.Theme.backgroundColor;
export const primaryColor = (props) => props.theme.Theme.primaryColor;
export const secondaryColor = (props) => props.theme.Theme.secondaryColor;
export const highlightColor = (props) => props.theme.Theme.highlightColor;
export const textColor = (props) => props.theme.Theme.textColor;
export const errorColor = (props) => props.theme.Theme.errorColor;
export const terciaryColor = (props) => props.theme.Theme.terciaryColor;
export const color10 = (props) => props.theme.Theme.color10;
export const color20 = (props) => props.theme.Theme.color20;
export const color30 = (props) => props.theme.Theme.color30;
export const color40 = (props) => props.theme.Theme.color40;
export const color50 = (props) => props.theme.Theme.color50;
export const color60 = (props) => props.theme.Theme.color60;
export const color70 = (props) => props.theme.Theme.color70;
export const colorHeader = (props) => props.theme.Theme.backgroundColor === '#f9f9f9' ?  '#0ca5c0' : 'transparent';
